# Actuator, Prometheus 모니터링 설정
management:
  metrics:
    tags:
      application: q-asker-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
        gemini.chunk.duration: true
        gemini.request.first-quiz.duration: true
        gemini.request.total.duration: true
        gemini.request.spread.duration: true
  server:
    port: -1
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, conditions
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
