# AI (Google Gemini) 설정
spring:
  ai:
    retry:
      max-attempts: 1
    google:
      genai:
        chat:
          options:
            temperature: 1.0
            model: gemini-3-flash-preview
            max-output-tokens: 20000

q-asker:
  ai:
    chat-timeout-ms: 360000
    chunk:
      max-count-variants: 5
