spring:
  ai:
    google:
      genai:
        chat:
          options:
            temperature: 0.2

q-asker:
  ai:
    chunk:
      max-count-variants: 10, 5
    file-client:
      base-url: https://generativelanguage.googleapis.com
      connect-timeout-ms: 5000
      read-timeout-ms: 30000
