resilience4j:
  circuitbreaker:
    instances:
      aiServer:
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 3
        sliding-window-size: 10
        failure-rate-threshold: 60
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        event-consumer-buffer-size: 10
    metrics:
      enabled: true
