# SpringDoc OpenAPI / Swagger UI 설정
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    tagsSorter: alpha

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
