# 인증/보안 설정 (OAuth2, JWT)
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          google:
            scope:
              - profile
          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
    jwt:
      access-expiration-second: 86400 # 1일
      refresh-expiration-second: 2592000 # 30일
