language: "ko-KR"
early_access: false
reviews:
  profile: "chill"
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: false
    drafts: false
chat:
  auto_reply: true