spring:
  application:
    name: q-asker
  config:
    import:
      - config/database-config.yml
      - config/ai-setting.yml
      - config/spring-security.yml
      - config/oci-bucket-config.yml
      - config/jodconverter.yml
      - config/actuator.yml
      - config/app-common.yml
      - config/resilience.yml
      - config/spring-doc.yml
      - application-secrets.yml

