spring:
  application:
    name: q-asker
  config:
    import:
      - optional:classpath:config/server.yml
      - optional:classpath:config/security.yml
      - optional:classpath:config/monitoring.yml
      - optional:classpath:config/resilience4j.yml
      - optional:classpath:config/jodconverter.yml
      - optional:classpath:config/springdoc.yml
      - optional:classpath:config/ai.yml
      - optional:classpath:config/q-asker.yml
      - optional:classpath:config/aws.yml

