# 암호화된 민감 정보 (Jasypt ENC)

# == 공통 (local/prod 동일) ==
spring:
  ai:
    google:
      genai:
        api-key: ENC(QT6BgyfUJpU8eMQ1HeNsDMAO2F4vbCYclqSof8EFxzSqnuuH+rc74ep469JuWspP2N6lHjQvjROZlA6l2gXET1m3hsaLoVt0Rknj0tUTUlk=)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(0593mofGLE75PAcOa8zB+bXSiOIR0nQ4jsWA3ImEPCcK2FxyAhfuP6eUGR1uUvncSS2snsyRslNUSLR2+cxl8ZVXWBKmuM2Ps7WhDAo268xwW7/fws3QZVQLVjWmm1ADH3Kf6CBvUFkcnjswIQVV8g==)
            client-secret: ENC(1EMg5Pz7DW1Uu/8IjEFpwauY9MvhdCt3Ln6AkWfJrFTwksnqM9WA57Cpg0DDaaFF78/1hM3w2pLYIEJ3F3LUlrCE6C3QddPfz+O2Ef25RbI=)
          kakao:
            client-id: ENC(nS2+Q7HakEQ3Baz/0I9KLBqyrRVKZ7vkDPsNa6rXhIt6BYgWDBIEaR1/dnGYYiw7VqkF88wnO/UifvZioRaqsZ9NA8r5n5yOIz8YCUcJ5I8=)
            client-secret: ENC(QraIeB6b9pXrOyGWtFSMfgOv7xAQhpnIjeOBk6cBy52SizOS/8rv0jK6XmeIc1BtAFVCfxuESu4+xhuejTV8Tbm5i55nt+o+zo2f2moMv3s=)
    jwt:
      secret: ENC(Jeu3MuAaMOI3X+lLvscvqJCIYwjGacOoWze0XmTWV89W3F8QU2yucQO4kfXWuQgi)

aws:
  cloudfront:
    base-url: ENC(9+YmILh4Tu8KExN3af3xft6fqJBfi8THL8eIQE1RhDJfau54OHutWOvDpKhSHn5i02liSEoDGu6Ybcj6HiXGQA==)
  s3:
    bucket-name: ENC(6bv4SxOVgbybTERj+F8mOuH7FAuNlAy/y5AvBbWV4QdCbSh80SKXfLU3TUcwqHvN)
    access-key: ENC(7x9BtJh0XjTCqHk7wNaF6ZyiCt+7Mv+I8y7NS6bgY0vDKWzZiv06A/vAZ/5usAdd9KYInWPiYeaP/xKTX/+YIQ==)
    secret-key: ENC(0y4Bf3GdANSgrB7a8veXVwiBijhWfKzl+cXBI8TYBlwNToZAFeKR5P4bEQlrK6ggInxM1/UAeA7YAOEShFo74RfQfXk6SpAq7doxGZTeirI=)

q-asker:
  slack:
    webhook-url-notify: ENC(9gKy67mFwk2AbeisSdGxQQI6j/DIiKUZoWGzik3QCRvEQa49e6bQsJ69VmfI0cD5kR93TTg1rFl+0f5bnx3SBVKoVHhUUMRVxcN61iyUEMJe0svSRd71VT6Pz5193SJqm1OcULxDd6A8Ifqf0QwlGUULYcVMmTraugoHwvpB1e8=)
  hashid:
    salt: ENC(Y+PWwkcYm1pmuHBHW6O4MGw4sS3l/GZAkTxSoJ8Pi3Cp8buxGKyGD1QztMHnVScvHeqTbQJDC9UlKFaNcJ49LEy33dFYEQznm0U4AUCGyuU=)

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(q9J04PgT+4BYgYtwP6qOb2sw/JC35sBTz7L9+fLa0ikhV6yDOEzJ42x+CIuctwMNF5TpAYqHQ8btSj1nuQIXvqj8PIm3Mt8MahJwNgOMiU0=)
    username: ENC(LYWjA55X9QZr6a+1KfJ4eWOldtreaszO8UITl+snS6liMIlcqIahIbTjMjFHm5Sc)
    password: ENC(fSfnC/+3Dy6kj/N3KagZRCdDaQbYlv2AIPgYZ1l5PfKjY9euuXCEmosIRgVgFQsE)
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ENC(HGug7tWS1cS+GLES/3w6Y/OwHki8eS5I/sBRWfHXi6BYxFkx7lUZf/Lcm3HnpJAN7ZMMgrFfU6wRqustTazlIpfd55Qy4n7XoCq1OD/aC60=)
          kakao:
            redirect-uri: ENC(SpYenEM5g7HtdeF5yOy/8vTGuPsKDLwWQNrZ5g++zwhTNkt1Gw0ImO7cwnZ3VGdhB6TblMdpxaDFkI6z4A/IvQbE0mjhNS2oHvj0NycZ2Aw=)

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ENC(QP+Ah9q1tYRGUcI7USqcYnheWLcTTyZb90ml01JWtx1/8uHCxaIoE3xcuHWKqWHXxeEFhNUho9w33suKREEnKNACidkXl1kX2msBefLrgpg=)
    username: ENC(Y3F+qcIHIBDKRcSxqix4MtlfgqrkWHnpM40NR3olBCFZPLXLlDQ0mIB+Qir+wOgp)
    password: ENC(t4z8CRcdTCmysr++wuxwSmDyxRikXbmxxYeRdgMTA0g49iPS+46VOyxS/0TAeecl)
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ENC(UvXNyNlvsgXLypPVzEJku6NO/gUbxwCm1e8JoL0CDQbYYDSidJ9UkJcngdLxRtjXWbDfp+A9tGDf2vd7YCSh2j+26AowoL1KZrXzradltXBbfctj6fmCNtHxFHeFc4pG)
          kakao:
            redirect-uri: ENC(BD99QlSvN6a0chwGqE/cZocBScM7snH/Ex6WR3xEpaAqqlAAWskEo0JoCPOQOqtTDH4DWeQJTdM02WoOWDDNuyBluXeULldOHCOpwvE5tLg=)
