spring:
  application:
    name: q-asker
  config:
    import:
      - config/server.yml
      - config/ai.yml
      - config/security.yml
      - config/aws.yml
      - config/jodconverter.yml
      - config/monitoring.yml
      - config/q-asker.yml
      - config/resilience4j.yml
      - config/springdoc.yml
      - config/secrets/server.yml
      - config/secrets/ai.yml
      - config/secrets/security.yml
      - config/secrets/aws.yml
      - config/secrets/jodconverter.yml
      - config/secrets/q-asker.yml

logging:
  level:
    org.glowroot: OFF
