# AI API 키 및 모델 파라미터 (암호화)

---
spring:
  config:
    activate:
      on-profile: local
  ai:
    google:
      genai:
        api-key: ENC(rQ08l7ghNtcnFDzAR7sl337RkSU6zrnI0eX1XvWfzx7ax9yCq/c2O/pUXMknZ2mWkI2WPKv54YHMaevydtjQ6sL3kRPdGDJkZS0rd4bJMXM=)
        chat:
          options:
            model: ENC(m3SA0/hIxisrMtrlU+Lo+u8RN8Yv8k5lKzlSy3yKUQnQH7Cy4iDuG/IYO3M4A3h//MoAZEdFT/Gt4gF/ooHLkQ==)
            thinking-budget: ENC(ve0ZzJ3830k3mPm+6RiikH0CUTCc21xi2YFlrhfxT9jAXM6MJ8aQm7W5JEdY2qb3)

---
spring:
  config:
    activate:
      on-profile: prod
  ai:
    google:
      genai:
        api-key: ENC(ckGk9OJCuH5b8kuogFhhBPzd1vyriUPV/bySYiKDmwQ6B993bJkK16uAcanPA4/+H3/dxcsNAqTQyDNzSXGoQjvbC+wOUxYVWs8qm4l/Os0=)
        chat:
          options:
            model: ENC(m3SA0/hIxisrMtrlU+Lo+u8RN8Yv8k5lKzlSy3yKUQnQH7Cy4iDuG/IYO3M4A3h//MoAZEdFT/Gt4gF/ooHLkQ==)
            thinking-budget: ENC(kDNLaWQSoBM2XwTjFldaHUBgTk3K73jfGg6wms/9G7AY6550b2CNXZDqo26o74k2)