# AWS 자격증명 및 리소스 정보 (암호화)
aws:
  cloudfront:
    base-url: ENC(9+YmILh4Tu8KExN3af3xft6fqJBfi8THL8eIQE1RhDJfau54OHutWOvDpKhSHn5i02liSEoDGu6Ybcj6HiXGQA==)

---
spring:
  config:
    activate:
      on-profile: local

aws:
  s3:
    bucket-name: ENC(6bv4SxOVgbybTERj+F8mOuH7FAuNlAy/y5AvBbWV4QdCbSh80SKXfLU3TUcwqHvN)
    access-key: ENC(7x9BtJh0XjTCqHk7wNaF6ZyiCt+7Mv+I8y7NS6bgY0vDKWzZiv06A/vAZ/5usAdd9KYInWPiYeaP/xKTX/+YIQ==)
    secret-key: ENC(0y4Bf3GdANSgrB7a8veXVwiBijhWfKzl+cXBI8TYBlwNToZAFeKR5P4bEQlrK6ggInxM1/UAeA7YAOEShFo74RfQfXk6SpAq7doxGZTeirI=)

---
spring:
  config:
    activate:
      on-profile: prod

aws:
  s3:
    bucket-name: ENC(Z1NQ7lzwcKR2Y2N7JNp21RejuYCo7YBSuTmgNiQhOIkAqKhmeF1VmFIr1D83hj+4)
    access-key: ENC(1UffDLw28yIO8x1cu+0PnZ7Q9CK0mhcHPiH6YPUXq8w6Gt/sfpFGKvmDrHRgp/OvLzVhYWNj6WKkbvFN3RwcZw==)
    secret-key: ENC(W48k3HqWXvR+iAQP1LEHx3t3X3I4ZscUJVupNMmyw4NYbDZNOEXRVQ5cXmSOfMK/RIW/XOuPcpNEtLV/S2axHD8EHJXEXZMxGJvVg1fj6J8=)