# Q-Asker 민감 정보 (암호화)

---
spring:
  config:
    activate:
      on-profile: local

q-asker:
  slack:
    webhook-url-notify: ENC(9gKy67mFwk2AbeisSdGxQQI6j/DIiKUZoWGzik3QCRvEQa49e6bQsJ69VmfI0cD5kR93TTg1rFl+0f5bnx3SBVKoVHhUUMRVxcN61iyUEMJe0svSRd71VT6Pz5193SJqm1OcULxDd6A8Ifqf0QwlGUULYcVMmTraugoHwvpB1e8=)
  hashid:
    salt: ENC(Y+PWwkcYm1pmuHBHW6O4MGw4sS3l/GZAkTxSoJ8Pi3Cp8buxGKyGD1QztMHnVScvHeqTbQJDC9UlKFaNcJ49LEy33dFYEQznm0U4AUCGyuU=)

---
spring:
  config:
    activate:
      on-profile: prod

q-asker:
  slack:
    webhook-url-notify: ENC(2xCju22m5zGyqeh3l1xeA36Cm+sRjA7PO/RGEh/EMd0LKCkgTzLTCZPc1wSqV3rErHNhn3dcOCa18CZeFo/tSOhRVm8Pe2v0/rR533oNAuXaz5+TMWFVwCO60Yxv5k/zrodD6lBBpzcQIWMwHoYMl5BCnhfMAtRupoPMtVFUdtU=)
  hashid:
    salt: ENC(Lp2AuuDBujVbYhnkXP2wlQos1qJy20JQkMP+mNY2wgShCew/bsz3VfdDVq/qCo2VDqEaPgeYTIKRWJ4gTbNGwZpG97Hs3I5VIynJElzTz0M=)
  web:
    frontend-deploy-url: ENC(Yz0KRDYezAjW1jFXqbEwYudwxJr0/7EOB5sTX5lq2Nk+M3ONR7tXg0R9xucGdiMTNpTkwxijVFP3GUrQ9THH7A==)
    frontend-dev-url: ENC(3Z3bkGdBFY0sUvQLfqyi4HveAZ5qqH5vaJnC+vewLwLElhD5+3OhIoDtFOZOblAzZ+3qtj7vQSvBjd++JpILPm+3NDSfeCblK9JmpoLgIX1tQ5CzNyzEz8+DYGIjGQIHflNxgMSZ3vRwec3upKFaTw==)