# OAuth2 클라이언트 자격증명 및 JWT 시크릿 (암호화)

---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(0593mofGLE75PAcOa8zB+bXSiOIR0nQ4jsWA3ImEPCcK2FxyAhfuP6eUGR1uUvncSS2snsyRslNUSLR2+cxl8ZVXWBKmuM2Ps7WhDAo268xwW7/fws3QZVQLVjWmm1ADH3Kf6CBvUFkcnjswIQVV8g==)
            client-secret: ENC(1EMg5Pz7DW1Uu/8IjEFpwauY9MvhdCt3Ln6AkWfJrFTwksnqM9WA57Cpg0DDaaFF78/1hM3w2pLYIEJ3F3LUlrCE6C3QddPfz+O2Ef25RbI=)
            redirect-uri: ENC(HGug7tWS1cS+GLES/3w6Y/OwHki8eS5I/sBRWfHXi6BYxFkx7lUZf/Lcm3HnpJAN7ZMMgrFfU6wRqustTazlIpfd55Qy4n7XoCq1OD/aC60=)
          kakao:
            client-id: ENC(nS2+Q7HakEQ3Baz/0I9KLBqyrRVKZ7vkDPsNa6rXhIt6BYgWDBIEaR1/dnGYYiw7VqkF88wnO/UifvZioRaqsZ9NA8r5n5yOIz8YCUcJ5I8=)
            client-secret: ENC(QraIeB6b9pXrOyGWtFSMfgOv7xAQhpnIjeOBk6cBy52SizOS/8rv0jK6XmeIc1BtAFVCfxuESu4+xhuejTV8Tbm5i55nt+o+zo2f2moMv3s=)
            redirect-uri: ENC(SpYenEM5g7HtdeF5yOy/8vTGuPsKDLwWQNrZ5g++zwhTNkt1Gw0ImO7cwnZ3VGdhB6TblMdpxaDFkI6z4A/IvQbE0mjhNS2oHvj0NycZ2Aw=)
    jwt:
      secret: ENC(Jeu3MuAaMOI3X+lLvscvqJCIYwjGacOoWze0XmTWV89W3F8QU2yucQO4kfXWuQgi)

---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(GA/lqJZ69ef0rztXruA8XnEt+7a5gWekQ9jtey+pFcb8jRjZpKyIGPmGptDuASc8jMxJVx/qiOOtr+luSOtyMScDiyFZ+trAhJo5e3cmmp3W5xUSNq0CdoZ6D8FO5i4zH9pQBGfci5O835gBKT60EA==)
            client-secret: ENC(YLABT7DQx6sH6ENzun6cDyCPk1THCIdPUHHPDNJPConcHDnZssCRQhmKk1yQPY8Wkn9kQQcNG0CZwn8M+H78RfX1+WuUwgL8ogvYNWwcTrk=)
            redirect-uri: ENC(UvXNyNlvsgXLypPVzEJku6NO/gUbxwCm1e8JoL0CDQbYYDSidJ9UkJcngdLxRtjXWbDfp+A9tGDf2vd7YCSh2j+26AowoL1KZrXzradltXBbfctj6fmCNtHxFHeFc4pG)
          kakao:
            client-id: ENC(jafqpth6rlvzSBfpfHMf+EzNYsuTccHRP7OYmWyiJxSAYeuDBLFtKvCOnY2Ry2r6GSG7mTmMAqyzLKCmduh9tJp6xmJpHLAmWhVRoBhR0mw=)
            client-secret: ENC(kyqzfkzmZqVRMVa3bT9mat+0BM1uPN4I82qfZVWXumwyQO/OluG9C+hUQMOsJ/06EftT6TQeeuCCACZivKKVwjLjP5Jz7TvEeHpl+ZJhhFA=)
            redirect-uri: ENC(BD99QlSvN6a0chwGqE/cZocBScM7snH/Ex6WR3xEpaAqqlAAWskEo0JoCPOQOqtTDH4DWeQJTdM02WoOWDDNuyBluXeULldOHCOpwvE5tLg=)
    jwt:
      secret: ENC(kZYJ6oUWb/b3JTVXUNWRUgNEnC8eG5mVVRmzfWWlPjr+yaRe1dAyVv42N19/PAD6)