# DB 접속 정보 (암호화)

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(q9J04PgT+4BYgYtwP6qOb2sw/JC35sBTz7L9+fLa0ikhV6yDOEzJ42x+CIuctwMNF5TpAYqHQ8btSj1nuQIXvqj8PIm3Mt8MahJwNgOMiU0=)
    username: ENC(LYWjA55X9QZr6a+1KfJ4eWOldtreaszO8UITl+snS6liMIlcqIahIbTjMjFHm5Sc)
    password: ENC(fSfnC/+3Dy6kj/N3KagZRCdDaQbYlv2AIPgYZ1l5PfKjY9euuXCEmosIRgVgFQsE)

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ENC(QP+Ah9q1tYRGUcI7USqcYnheWLcTTyZb90ml01JWtx1/8uHCxaIoE3xcuHWKqWHXxeEFhNUho9w33suKREEnKNACidkXl1kX2msBefLrgpg=)
    username: ENC(Y3F+qcIHIBDKRcSxqix4MtlfgqrkWHnpM40NR3olBCFZPLXLlDQ0mIB+Qir+wOgp)
    password: ENC(t4z8CRcdTCmysr++wuxwSmDyxRikXbmxxYeRdgMTA0g49iPS+46VOyxS/0TAeecl)