services:
  q-asker-mysql:
    image: mysql:latest
    container_name: q-asker-db
    restart: no
    command: >
      --innodb-buffer-pool-size=4G
      --innodb-buffer-pool-instances=4
      --innodb-flush-log-at-trx-commit=1
      --max-connections=200
      --innodb-io-capacity=625
      --innodb-io-capacity-max=10000
      --innodb-read-io-threads=1
      --innodb-write-io-threads=4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - q-asker-db:/var/lib/mysql

volumes:
  q-asker-db:
    external: true
    name: api_q-asker-db
