name: Docker Hub Push & 개발 서버 EC2 배포

on:
  push:
    branches:
      - ICC-68-swagger-newrelic
  workflow_dispatch:

jobs:
  build:
    name: 빌드 작업
    runs-on: ubuntu-latest

    env:
      APPLICATION_PROD_YML: ${{ secrets.APPLICATION_PROD_YML }}
      NEWRELIC_YML: ${{ secrets.NEWRELIC_YML }}
      DOCKER_IMAGE_NAME: api
      DOCKER_ID: ${{ secrets.DOCKER_ID }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 설정
        uses: gradle/gradle-build-action@v2

      - name: newrelic.yml 등록
        run: |
          echo "${{ env.NEWRELIC_YML }}" > newrelic/newrelic.yml

      - name: application-prod.yml 등록
        run: |
          echo "${{ env.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml

      - name: gradle.properties 등록
        run: |
          echo DOCKER_ID="${{ env.DOCKER_ID }}" >> gradle.properties
          echo DOCKER_PASSWORD="${{ env.DOCKER_PASSWORD }}" >> gradle.properties
          echo DOCKER_IMAGE_NAME="${{ env.DOCKER_IMAGE_NAME }}" >> gradle.properties

      - name: Docker Hub에 로그인
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_ID }}" --password-stdin

      - name: Jib로 Docker 이미지 빌드 및 푸시
        run: ./gradlew jib -Pprofile=prod

  deploy:
    name: 개발 서버 EC2 배포
    needs: build
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

      # Docker 관련
      CONTAINER_NAME: q-asker-api-server
      DOCKER_IMAGE_NAME: api
      DOCKER_ID: ${{ secrets.DOCKER_ID }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: EC2에 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          debug: true
          script: |
            echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_ID }}" --password-stdin
            docker pull ${{ env.DOCKER_ID }}/${{ env.DOCKER_IMAGE_NAME }}
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d --name ${{ env.CONTAINER_NAME }} -p 8080:8080 ${{ env.DOCKER_ID }}/${{ env.DOCKER_IMAGE_NAME }}
            docker image prune -af