name: Docker Hub Push & 개발 서버 EC2 배포
on:
  push:
    branches:
      - ICC-150-cd
  workflow_dispatch:

jobs:
  build:
    name: 빌드 작업
    runs-on: ubuntu-latest
    env:
      APPLICATION_PROD_YML: ${{ secrets.APPLICATION_PROD_YML }}
      NEWRELIC_YML: ${{ secrets.NEWRELIC_YML }}
      GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 환경변수들 등록
        run: |
          echo "${{ env.NEWRELIC_YML }}" > newrelic/newrelic.yml
          echo "${{ env.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml
          echo "${{ env.GRADLE_PROPERTIES }}" > gradle.properties

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 설정
        uses: gradle/gradle-build-action@v2

      - name: Jib로 Docker 이미지 빌드 및 푸시
        run: ./gradlew jib

      - name: deploy 작업에 변수 넘기기
        id: set_outputs
        run: |
          DOCKER_ID_VALUE=$(grep '^DOCKER_ID=' gradle.properties | cut -d'=' -f2-)
          echo "::add-mask::$DOCKER_ID_VALUE" 
          echo "docker_id=$DOCKER_ID_VALUE" >> $GITHUB_OUTPUT
          
          DOCKER_IMAGE_NAME_VALUE=$(grep '^DOCKER_IMAGE_NAME=' gradle.properties | cut -d'=' -f2-)
          echo "::add-mask::$DOCKER_IMAGE_NAME_VALUE" 
          echo "docker_image_name=$DOCKER_IMAGE_NAME_VALUE" >> $GITHUB_OUTPUT
          
          DOCKER_PASSWORD_VALUE=$(grep '^DOCKER_PASSWORD=' gradle.properties | cut -d'=' -f2-)
          echo "::add-mask::$DOCKER_PASSWORD_VALUE" 
          echo "docker_password=$DOCKER_PASSWORD_VALUE" >> $GITHUB_OUTPUT

  deploy:
    name: 개발 서버 EC2 배포
    needs: build
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
      DOCKER_ID: ${{ needs.build.outputs.docker_id }}
      DOCKER_IMAGE_NAME: ${{ needs.build.outputs.docker_image_name }}
      DOCKER_PASSWORD: ${{ needs.build.outputs.docker_password }}

    steps:
      - name: EC2에 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          debug: true
          script: |
            echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_ID }}" --password-stdin
            docker pull ${{ env.DOCKER_ID }}/${{ env.DOCKER_IMAGE_NAME }}
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d --name ${{ env.CONTAINER_ID }}-${{ env.DOCKER_IMAGE_NAME }} -p 8080:8080 -p 9999:9999 ${{ env.DOCKER_ID }}/${{ env.DOCKER_IMAGE_NAME }}
            docker image prune -af